### PR TITLE
Support for history when in interactive mode

### PR DESCRIPTION
**Pull request by fpighi**
Hi, I've noticed that when I switched to interactive mode the arrow keys were producing [[A, [[B and so on.

It turns out that there's a simple way of fixing this behaviour by importing the readline module.

It works for me with this import, not sure if it could cause other problems. If you like it feel free to pull this into your repo.

Thanks, awesome tool!

### CODE REVIEW

**Comment by inglesp** [comment]
Hi Franceso,

Thanks for the pull request!  I think we'd need to ensure that nothing
untoward happened if readline wasn't present, which I think is the case on
Windows.  Passing on the ImportError would be enough.  I'd be happy to
merge that in if you could make that change.  You could also experiment
with the rlcompleter module to get tab completion if you're feeling
adventurous!

Cheers,

Peter.

**Comment by fpighi** [comment]
You are right... readline is not there on Windows. I will trap the ImportError and will test it a little bit before submitting another pull request then. Thanks for the heads up on the rlcompleter as well... will surely do, I'm learning Python and it would be a good thing to try out.

**Comment by fpighi** [comment]
I've tested on Windows and it works fine, with no history but at least it doesn't break.

**Comment by inglesp** [comment]
Sorry for sitting on this for so long!  I've just added readline support in https://github.com/inglesp/prescons/commit/b9771cadd4835bdeb0fbfeb1380d603df022a33a.

**Pull request closed without merging**
